# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  machine:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout

  build:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - run: 
          name: Build
          command: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  bundle_dependencies:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: Firebase Tools Install
          command: npm install -g firebase-tools
      - run:
          name: Install SASS
          command: npm install node-sass sass-loader --save-dev
      - run:
          name: Install Production Dependencies
          command: npm install moment vue-router bulma firebase vuefire font-awesome vue-quill-editor --save         
        
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: Firebase Deploy
          command: bash .circleci/setup-heroku.sh

      - run:
          name: Set Firebase Deploy Key
          command: firebase use --token $FIREBASE_DEPLOY_KEY $FIREBASE_APP_NAME
      - run:
          name: Deploy to Firebase
          command: firebase deploy -m "Pipeline $CIRCLE_SHA1, build $CIRCLE_BUILD_NUM" --non-interactive --token $FIREBASE_DEPLOY_KEY



workflows:
  version: 2
  build_and_deploy:
    jobs:
      - machine
      - build
      - deploy:
          requires:
            - machine
            - bundle_dependencies
            - build
          filters:
            branches:
              only: master
  build_and_test:
    jobs:
      - machine
      - build 